<?php

namespace app\modules\weixin\controllers;

use yii\web\Controller;


class DefaultController extends Controller
{
    //public $token;
    // ngrok authtoken 48v5HDwyRoie4edazXq7B_5S2wNm1whz4gkTouwaTAV
    // ngrok http 80
    //public $ngroktoken ='48v5HDwyRoie4edazXq7B_5S2wNm1whz4gkTouwaTAV';

//    public function init()
//    {
//        $cache = \Yii::$app->cache;
//        $key = 'weixin_token';
//        $this->token = $cache->getOrSet($key,function(){
//            // 获得token
//            return 1;
//        },3600);
//        parent::init(); // TODO: Change the autogenerated stub
//    }

    public function actionIndex()
    {
        header('content-type:text');
        $nonce     = $_GET['nonce'];
        $token     = 'zhangfei';
        $timestamp = $_GET['timestamp'];
        $echostr   = $_GET['echostr'];
        $signature = $_GET['signature'];
        //形成数组，然后按字典序排序
        $array = array();
        $array = array($nonce, $timestamp, $token);
        sort($array);
        //拼接成字符串,sha1加密 ，然后与signature进行校验
        $str = sha1( implode( $array ) );
        ob_clean();
        if( $str == $signature && $echostr ){
            //第一次接入weixin api接口的时候
            echo  $echostr;
            exit;
        }


    }

}
