<?php
/**
 * Created by PhpStorm.
 * User: 张鹏飞
 * Date: 2018/1/5
 * Time: 17:44
 */

namespace app\modules\v1\controllers;


use app\modules\v1\models\Comment;

class CommentController extends DefaultController
{
    public $typeIdArr;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->typeIdArr  =       \Yii::$app->params['typeid'];

    }

    // 评论列表
    public function actionCommentList()
    {
        $request    =       \Yii::$app->request;
        $articleid  =       $request->get('id',0);
        $typeid     =       $request->get('typeid');
        $page       =       $request->get('page',1);

        if(!in_array($typeid,array_values($this->typeIdArr)))
            return ['code'=>403,'msg'=>'参数错误','data'=>''];

        $comment    =       Comment::getCommentByPageLevel($typeid,$articleid,$page);
        
        if($comment){
            $app_url    =   \Yii::$app->params['app_url'];

            foreach ($comment['commentlist'] as $k=>$v){
                // 处理用户头像
                if($v['headpic'])
                    $comment['commentlist'][$k]['headpic'] = $app_url . $v['headpic'];

                // 处理虚拟用户头像
                if($v['vr_headpic'])
                    $comment['commentlist'][$k]['headpic'] = $app_url . $v['vr_headpic'];

                // 处理用户昵称 - 若vr_headpic存在则为昵称
                $v['vr_nickname']? $comment['commentlist'][$k]['nickname'] =  $v['vr_nickname'] : $comment['commentlist'][$k]['nickname'] =  $v['nickname'];
                if(!$v['nickname'] && !$v['vr_nickname']) $comment['commentlist'][$k]['nickname'] = '匿名用户';

                // 处理dockid 也就是用户是否为回复
                unset($comment['commentlist'][$k]['vr_headpic']);
                unset($comment['commentlist'][$k]['vr_nickname']);
            }

            // 对null值进行处理 - 前段要求   `-`
            foreach ($comment['commentlist'] as $k=>$v)
            {
                foreach ($v as $vk=>$vv)
                {
                    if(is_null($v[$vk])) $comment['commentlist'][$k][$vk] = '';
                }
            }
            return ['code'=>200,'data'=>$comment,'msg'=>'ok'];
        }
        else
        {
            return ['code'=>404,'data'=>'','msg'=>'未找到数据'];
        }
    }


    // 添加评论
    public function actionAdd()
    {
        if(!$this->logsign) return ['code'=>401,'msg'=>'用户未登录','data'=>null];
        $request        =       \Yii::$app->request;
        $content        =       $request->post('content');
        $typeid         =       $request->post('typeid',0);
        $articleid      =       $request->post('id');
        $memberid       =       $this->mid;
        $is_anonymous   =       $request->post('is_anonymous',1);
        $dockid         =       $request->post('replyid',0);

        if(!in_array($typeid,array_values($this->typeIdArr))
            || empty($content) || empty($articleid))
            return ['code'=>403,'msg'=>'参数错误','data'=>''];

        $data           =       [
            'content'   =>       strip_tags($content),
            'typeid'    =>       (int)$typeid,
            'articleid' =>       (int)$articleid,
            'memberid'  =>       (int)$memberid,
            'dockid'    =>       (int)$dockid,
            'addtime'   =>       time(),
        ];
        // 若是匿名登录 , 则默认昵称为昵称用户
        if($is_anonymous) $data['vr_nickname'] = '匿名用户';

        $re =  \Yii::$app->db->createCommand()->insert(Comment::tableName(),$data)->execute();

        if($re)
            return ['code'=>200,'msg'=>'ok','data'=>''];
        else
            return ['code'=>400,'msg'=>'失败','data'=>''];




    }


}