<?php
/**
 * Created by PhpStorm.
 * User: 张鹏飞
 * Date: 2018/1/2
 * Time: 16:01
 */

namespace app\modules\v1\controllers;



use app\modules\v1\models\MemberAddress;

class MemberAddressController extends DefaultController
{
    public function beforeAction($action)
    {
        if (!$this->logsign) {
            echo json_encode(['code' => 401, 'msg' => '用户未登录', 'data' => '']);
            exit();
        }

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    // 根据id获取用户信息
    public function actionAddressDetail()
    {
        $id     =       \Yii::$app->request->get('id',0);
        $address = MemberAddress::detail($id);
        if(empty($address))
            return ['code'=>404,'msg'=>'未找到数据','data'=>''];
        else
            return ['code'=>200,'msg'=>'ok','data'=>$address];
    }

    // 用户地址列表
    public function actionLister()
    {
        $mid        =       $this->mid;
        $address    =       MemberAddress::lister($mid);
        if(empty($address))
            return  ['code'=>200,'msg'=>'数据未找到','data'=>''];
        else
            return ['code'=>200,'msg'=>'ok','data'=>$address];
    }

    // 新增或者修改数据-根据id判断
    public function actionAddressAdd()
    {
        $request    =       \Yii::$app->request;
        $mid        =       $this->mid;
        $id         =       $request->post('id',null);
        $data       =       [
            'memberid'  =>  $mid,
            'province'  =>  $request->post('province'),
            'city'      =>  $request->post('city'),
            'address'   =>  $request->post('address'),
            'postcode'  =>  $request->post('postcode'),
            'receiver'  =>  $request->post('receiver'),
            'phone'     =>  $request->post('phone'),
            'is_default'=>  $request->post('is_default',0),
        ];

        if(empty($data['province']) || empty($data['city']) || empty($data['address'])  || empty($data['receiver']) || empty($data['phone']))
            return ['code'=>403,'data'=>'','msg'=>'请填写必填信息'];

        // 存数据或者修改数据 id存在则为修改
        if($id)
            $re = MemberAddress::updateAll($data,'memberid='.$mid . ' and id = '.$id);
        else
            $re = \Yii::$app->db->createCommand()->insert(MemberAddress::tableName(),$data)->execute();

        // 对插入数据进行判断
        if(!$re)
            return ['code'=>403,'msg'=>'新增失败','data'=>''];

        if(!$id)
            $id = \Yii::$app->db->getLastInsertID();

        // 对其它数据进行更新
        if($re !== false && $data['is_default'] == 1)
            $re = MemberAddress::updateAll(['is_default' => 0],'memberid='.$mid . ' and id != '.$id);

        return  ['code'=>200,'msg'=>'操作成功','data'=>''];

    }

    // 删除用户地址数据
    public function actionAddressDelete()
    {
        $mid        =       $this->mid;
        $id         =       \Yii::$app->request->get('id');
        $re         =       MemberAddress::deleteAll(['id'=>$id,'memberid'=>$mid]);
        if($re)
            return  ['code'=>200,'msg'=>'ok','data'=>''];
        else
            return ['code'=>200,'msg'=>'删除失败','data'=>''];
    }

}