<?php
/**
 * Created by PhpStorm.
 * User: 张鹏飞
 * Date: 2018/1/4
 * Time: 14:07
 */

namespace app\modules\v1\controllers;


use app\modules\v1\models\Comment;
use app\modules\v1\models\Notes;

class NotesController extends DefaultController
{
    private $_typeid;
    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
        $this->_typeid  =   \Yii::$app->params['typeid']['notes'];

    }

    // 游记首页-获取最新new  全部all
    public function actionNotesIndex()
    {
        $newNotes       =   Notes::getNew();
        $recommend      =   Notes::getRecommend();
        $app_url        =   \Yii::$app->params['app_url'];
        // 处理图片和内容的图片url替换
        foreach ($newNotes as $k=>$v)
        {
            $newNotes[$k]['litpic'] =   $app_url . $v['litpic'];
        }

        foreach ($recommend as $k=>$v)
        {
            $recommend[$k]['litpic']    =   $app_url . $v['litpic'];
        }

        return ['code'=>200,'msg'=>'ok','data'=>['newnotes'=>$newNotes,'recommend'=>$recommend]];

    }

    // 排序列表 包括搜索
    public function actionNotesLister()
    {
        $request    =       \Yii::$app->request;
        $keyword    =       htmlentities(strip_tags($request->get('keyword',null)));
        $page       =       (int) $request->get('page',1);

        if($keyword)
            \Yii::$app->runAction('v1/search-keyword/add',['keyword'=>$keyword]);


        // 获取列表
        $notes = Notes::getLister($page,$keyword);
        if(!$notes) {
            $notes['notes'] = [];
            return ['code' => 200, 'msg' => '未找到数据', 'data' => $notes];
        }
        // 处理图片信息
        $app_url        =       \Yii::$app->params['app_url'];
        foreach ($notes['notes'] as $k=>$v)
        {
            $notes['notes'][$k]['litpic']  =   $app_url . $v['litpic'];
        }
        return ['code'=>200,'msg'=>'ok','data'=>$notes];
    }

    // 详情页信息
    public function actionNotesDetail()
    {

        $id     =       \Yii::$app->request->get('id',null);
        if(!$id) return ['code'=>404,'msg'=>"参数不能为空",'data'=>''];
        $notes = Notes::getDetails($id);

        if(empty($notes)) return ['code'=>404,'msg'=>"信息未找到",'data'=>''];
        $api_url    =   \Yii::$app->params['api_url'];

        // 获得游记的详情 - 便于前段使用webview
        $notes['content_url']    =      $api_url . '/v1/detail?type=notesdetail&id=' . $id;
        // 根据id和typeid获得评论量
        $typeid         =   $this->_typeid;
        $commentcount   =   Comment::getCommentCountByTypeId($typeid,$id)['count'];
        $notes['commentcount'] = $commentcount;

        return ['code'=>200,'data'=>$notes,'msg'=>'ok'];

    }


}