<?php
/**
 * Created by PhpStorm.
 * User: 张鹏飞
 * Date: 2018/1/22
 * Time: 13:46
 */

namespace app\modules\v1\controllers;


use app\modules\components\helpers\MyDateFormat;
use app\modules\v1\models\Comment;
use app\modules\v1\models\Destinations;
use app\modules\v1\models\Photo;
use app\modules\v1\models\PhotoAttr;
use app\modules\v1\models\PhotoPicture;

class PhotoController extends DefaultController
{
    public $typeid;

    public function beforeAction($action)
    {
        $this->typeid = \Yii::$app->params['typeid']['photo'];
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    // 条件 - 总
    public function actionCondition()
    {
        $condition = [
            'city'=>$this->runAction('city'),
            'zonghe'=>$this->runAction('attr'),
            'screen'=>$this->runAction('sort'),
        ];

        return ['code'=>200,'data'=>$condition,'msg'=>'ok'];
    }

    // 条件 - 目的地
    public function actionCity()
    {
        $city = Destinations::getTengchongCity();
        array_unshift($city,['id'=>'0','kindname'=>'全城','pinyin'=>'allcity']);
        return $city;
    }

    // 条件 - 属性
    public function actionAttr()
    {
        $attr = PhotoAttr::getAllAttr();
        //增加全部全部
        array_unshift($attr,['id'=>'0','attrname'=>'全部','pid'=>'0','son'=>[['id'=>'0','attrname'=>'全部','pid'=>'0']]]);
        return $attr;
    }

    // 条件 - 排序
    public function actionSort()
    {
        $sort = [
            ['id'=>0,'attrname'=>'综合排序'],
            ['id'=>1,'attrname'=>'点击量最高'],
        ];
        return $sort;
    }

    // 列表
    public function actionLister()
    {
        $request        =       \Yii::$app->request;
        $param          =       $request->get('param');
        $page           =       $request->get('page',1);
        $keyword        =       htmlentities(strip_tags($request->get('keyword',null)));

        // 对参数进行处理
        $params         =        explode('-',$param);
        if(count($params) != 3)
            return ['code'=>200,'msg'=>'参数错误','data'=>null];
        // 根据参数获得数据
        $photoObj = new Photo();
        $photo = $photoObj->Lister($param,$page,$keyword);

        if(empty($photo))
            return ['code'=>200,'data'=>['photo'=>[],'pagecount'=>''],'msg'=>'没有数据'];

        $photoArr = $photo['photo'];
        // 处理封面图
        $app_url = \Yii::$app->params['app_url'];
        $typeid = 1;
        foreach ($photoArr as $k=>$v)
        {
            if(!empty($v['litpic']))
                $photoArr[$k]['litpic'] = $app_url . $v['litpic'];
            $photoArr[$k]['commentcount'] = Comment::getCommentCountByTypeId($typeid,$v['id']);
            $photoArr[$k]['photocount'] = PhotoPicture::getCountByPhotoId($v['id']);
        }
        $photo['photo'] = $photoArr;
        return ['code'=>200,'data'=>$photo,'msg'=>'ok'];
    }

    // 相册详情
    public function actionDetail()
    {
        $id = \Yii::$app->request->get('id',0);
        $photoObj = new Photo();
        $photoPicObj = new PhotoPicture();
        $photo = $photoObj->Detail($id);
        $photo['piccount'] = $photoPicObj->getCountByPhotoId($id);
        $photo['commentcount'] = Comment::getCommentCountByTypeId($this->typeid,$id);
        $lister = $photoPicObj->Lister($id);
        $app_url = \Yii::$app->params['app_url'];
        foreach ($lister as $k=>$v)
        {
            $photo['piclist'][] = $app_url . $v['litpic'];
        }


        return ['code'=>200,'data'=>$photo,'msg'=>'ok'];
    }

    // 点赞
    public function actionFavorite()
    {
        $mid = $this->mid;
        $id = \Yii::$app->request->get('id');
        if(!$mid)
            return ['code'=>401,'data'=>'','msg'=>'点赞失败,请登录'];
        $redis = \Yii::$app->redis;
        $key = 'photo:favorite:photoid:' . $id . ':mid:' . $mid;
        if($redis->get($key))
            return ['code'=>402,'data'=>'','msg'=>'您今天已赞过'];
        // 获取当天还剩下的时间秒数
        $lastSecond = MyDateFormat::lastSeconds();
        $redis->setex($key,$lastSecond,100);
        $photo = Photo::findOne($id);
        $photo->favorite = $photo->favorite + 1;
        $re = $photo->save();
        if($re)
            return ['code'=>200,'data'=>'','msg'=>'点赞成功'];
        else
            return ['code'=>405,'data'=>'','msg'=>'点赞失败'];
    }

}